// <auto-generated />
using System;
using Mensi.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mensi.Core.Data.Migrations
{
    [DbContext(typeof(MensiDbContext))]
    [Migration("20260824111317_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mensi.Core.Domain.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Mensi.Core.Domain.Cycle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Anovulatory")
                        .HasColumnType("boolean")
                        .HasColumnName("anovulatory");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<int?>("LengthDays")
                        .HasColumnType("integer")
                        .HasColumnName("length_days");

                    b.Property<int?>("LutealPhaseLength")
                        .HasColumnType("integer")
                        .HasColumnName("luteal_phase_length");

                    b.Property<int?>("OvulationDayConfirmed")
                        .HasColumnType("integer")
                        .HasColumnName("ovulation_day_confirmed");

                    b.Property<int?>("OvulationDayEstimated")
                        .HasColumnType("integer")
                        .HasColumnName("ovulation_day_estimated");

                    b.Property<int?>("PredictedLengthDays")
                        .HasColumnType("integer")
                        .HasColumnName("predicted_length_days");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .IsUnique();

                    b.ToTable("cycle", (string)null);
                });

            modelBuilder.Entity("Mensi.Core.Domain.DailyLog", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal?>("BbtCelsius")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("bbt_celsius");

                    b.Property<short?>("CervicalMucus")
                        .HasColumnType("smallint")
                        .HasColumnName("cervical_mucus");

                    b.Property<short?>("CrampSeverity")
                        .HasColumnType("smallint")
                        .HasColumnName("cramp_severity");

                    b.Property<short?>("CrampType")
                        .HasColumnType("smallint")
                        .HasColumnName("cramp_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short?>("FlowIntensity")
                        .HasColumnType("smallint")
                        .HasColumnName("flow_intensity");

                    b.Property<short?>("LhTest")
                        .HasColumnType("smallint")
                        .HasColumnName("lh_test");

                    b.Property<short[]>("Moods")
                        .IsRequired()
                        .HasColumnType("smallint[]")
                        .HasColumnName("moods");

                    b.Property<bool>("PeriodStart")
                        .HasColumnType("boolean")
                        .HasColumnName("period_start");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Date");

                    b.ToTable("daily_log", (string)null);
                });

            modelBuilder.Entity("Mensi.Core.Domain.IntercourseEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool?>("Protected")
                        .HasColumnType("boolean")
                        .HasColumnName("protected");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("intercourse_event", (string)null);
                });

            modelBuilder.Entity("Mensi.Core.Domain.IntercourseEvent", b =>
                {
                    b.HasOne("Mensi.Core.Domain.DailyLog", null)
                        .WithMany("Intercourse")
                        .HasForeignKey("Date")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mensi.Core.Domain.DailyLog", b =>
                {
                    b.Navigation("Intercourse");
                });
#pragma warning restore 612, 618
        }
    }
}
